const rhodeIslandData = {
    area: 1545, // square miles
    land: 1034, // square miles
    water: 511, // square miles
    population: 1098163, // as of 2020 census
    popRank: 45,
    popDensity: 1006, // people per square mile
    popDensityRank: 2,
    medianHouseholdIncome: 63870,
    shoreline: 400, // miles
    length: 48, // miles
    width: 37, // miles
    highestPoint: 812, // feet
    elevation: 200, // feet
    waterToLandRatio: 49.5, // percent water
    shorelineToLandRatio: 38.7, // percent shoreline
    // https://www.ri.gov/facts/trivia.php
    stateName: "Rhode Island",
    nicknames: ["The Ocean State", "Little Rhody"],
    motto: "Hope",
    anthem: "Rhode Island, It's for Me",
    seal: "https://upload.wikimedia.org/wikipedia/commons/9/96/Seal_of_Rhode_Island_%282021%29.svg",
    flag: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Rhode_Island.svg",
    size: {
        totalArea: "1,214 square miles",
        northToSouth: "48 miles",
        eastToWest: "37 miles",
    },

    geography: {
        landArea: "1,045 square miles",
        coastlineLength: "40 miles",
        totalShoreline: "384 miles",
        highestPoint: "Jerimoth Hill at 812 feet",
        tallestWaterfall: "Stepstone Falls at 12 feet",
    },
    cities: {
        largestCity: "Providence",
        capital: "Providence",
        retailCapital: "Warwick",
        famousFor: "Newport",
        navyBase: "Newport",
    },
    facts: [
        "Rhode Island was the last of the original thirteen colonies to become a state",
        "Shares a state water border with New York",
        "Home to the first National Lawn Tennis Championship in 1881",
        "St. Mary's, founded in 1828, is the oldest Roman Catholic parish",
        "The first open golf tournament in the US was in 1895",
        "The Flying Horse Carousel is the nation’s oldest carousel",
        "The first circus in the US was in Newport in 1774",
        "Ann and Hope was the first discount department store in the US",
        "Home to the Tennis Hall of Fame",
        "Known for making silverware and fine jewelry",
        "Home to the oldest schoolhouse in the US, built in 1716",
        "The longest running 4th of July observances since 1785 are in Bristol",
        "Touro Synagogue, built in 1763, is the oldest in North America",
        "The first state to declare independence from England",
        "The oldest Baptist Church in America, founded by Roger Williams in 1638",
        "Cogswell Tower, site of an Indian observation point",
        "World's largest bug on the roof of New England Pest Control",
        "The Independent Man, a statue atop the State House since 1899",
        "There is a replica of the Liberty Bell in the State House",
        "Judge Darius Baker imposed the first jail sentence for speeding in 1904",
        "Polo was played for the first time in the US in 1876",
        "The first Afro-American regiment fought in the Battle of Rhode Island",
        "George M. Cohan, born in 1878, wrote 'I'm a Yankee Doodle Dandy'",
        "The first British troops to squash the revolution landed in Newport",
        "Rhode Islanders first took military action against England by sinking 'The Gaspee'",
        "The first torpedo was launched in Newport",
        "The first steam engine was built in Providence",
        "The first cotton mill was built in Pawtucket",
        "The first strike in the US was in Pawtucket",
        "The longest running 4th of July parade in the US is in Bristol",
        "The first automobile race on a track was in Cranston in 1896",
        "The first automobile parade was in Newport in 1899",
        "The first Baptist Church in America was founded in Providence in 1671",
        "Newport's Pelham Street was the first in America illuminated by gaslight in 1806",
        "Watch Hill has the nation’s oldest continuously operating carousel since 1850",
        "The first nine hole golf course in America was in Newport in 1890",
        "The first strike in the US involving women occurred in Pawtucket in 1824",
        "Anne Franklin was the first woman newspaper editor in America in 1762",
        "The first state health laboratory was established in Providence in 1894",
        "The Rhode Island State House has the first all-marble dome built in the US",
        "The first lunch wagon in America was introduced in Providence in 1872",
        "A motion picture machine was patented in Providence in 1867",
        "H.P. Lovecraft, born in Providence in 1890, wrote horror fiction such as 'The Call of Cthulhu'",
        "Elisabeth Alden Pabodie, the first white girl born in New England (1623-1717), is buried in Little Compton",
        "The first U.S. National Men's Tennis Championship took place at Newport Casino in August 1881",
        "Roger Williams National Memorial, covering only 4.56 acres, is one of the smallest national parks in the U.S.",
        "In 1794, Nehemiah and Seril Dodge developed a method for plating base metal with gold, establishing the costume jewelry industry in Providence",
        "David Melville installed the first gas street-lamp in the U.S. outside his home in Newport in 1805",
        "The Flying Horse Carousel in Watch Hill, built around 1876, is the oldest operating chain-suspended carousel in the U.S.",
        "Rhode Island is one of five states without an official governor's residence, the others being Arizona, California, Idaho, and Massachusetts",
        "In 1854, Commodore Matthew Perry from Rhode Island led the voyage that opened Japan to world trade",
        "The Herreshoff Manufacturing Company in Bristol built the first primitive torpedo boat, Lightning, in 1876",
        "Approximately seventy-seven percent of Rhode Island's population lives within a fifteen-mile radius of Providence, the state capital",
        "On May 4, 1776, Rhode Island renounced allegiance to King George III, becoming the first colony to declare independence",
        "Rhode Island is the second most densely populated state, with an average of 1,021 persons per square mile based on 2015 estimates",
        "The first anti-slavery statute in the American Colonies was passed in Rhode Island in 1652, but it was never enforced",
        "Rhode Island and Florida are the only two states that begin with a double consonant",
        "Up until 2020, Rhode Island was officially known as the State of Rhode Island and Providence Plantations",
        "Providence's Benefit Street, known as the 'Mile of History,' is believed to have the largest collection of historic buildings in their original locations in the U.S.",
        "The first Baptist Church in America was established by Roger Williams in Providence in 1638",
        "On December 21, 1790, the first American cotton mill began operation in Pawtucket, marking the start of the Industrial Revolution in the U.S.",
        "The Redwood Library and Athenaeum, established in Newport in 1747, is the oldest community library still occupying its original building in the U.S.",
        "In 1856, the B.B. & R. Knight Corporation began producing cloth under the 'Fruit of the Loom' label at Pontiac Mills in Warwick",
        "Rhode Island is one of four states where alcohol cannot be purchased in grocery stores, the others being Alaska, Maryland, and Delaware",
        "Walter Scott introduced the concept of the diner in 1872 with his horse-drawn lunch cart in Providence",
        "Rhode Island has the highest density of shipwrecks per square mile, with 3,403 known maritime 'incidents' documented by the Beavertail Lighthouse Museum Association as of 2020",
        "Rhode Island had 6,000 farms in 1880. By 2020, the number of 'farm operations' reported by the USDA was 1,100",
        "Since 1785, Bristol has hosted the nation's longest-running, continuous series of 4th of July celebrations",
        "Rhode Island's state motto, 'Hope,' is the shortest motto of any state",
        "Before the Boston Tea Party (1773) and the Battle of Lexington (1775), Rhode Island patriots burned the British revenue schooner Gaspee at Namquit Point in 1772",
        "In 1792, Elijah Ormsbee piloted one of the first steam-powered boats, the 'Experiment,' from Pawtucket to Providence",
        "The Narragansett Pacer, the first truly American breed of horse, was developed in Rhode Island in the 1700s",
        "The U.S. one dollar bill, redesigned in 1869, features a portrait of George Washington painted by Rhode Islander Gilbert Stuart in 1796",
        "In 1774, Rhode Island became the first colony to ban the importation of slaves",
        "In 1854, Rhode Island reduced its number of capitals from five to two, and finally to one in 1901",
        "Rhode Island has forty-five National Historic Landmarks, which is 1.73% of the 2,600 landmarks in the U.S.",
        "Rhode Island's reluctance to ratify the U.S. Constitution until May 29, 1790, was due in part to the debate over the addition of a bill of rights",
        "Rhode Island has the highest density of shipwrecks per square mile compared to any other state",
        "Touro Synagogue in Newport, built in 1763, is the oldest surviving synagogue building in the U.S.",
        "By the 1840s, Central Falls had the highest population density of any U.S. city",
        "The first natural-gas powered streetcar ran in Providence in 1873, designed by George B. Brayton",
        "The First Rhode Island Regiment, the first black American army unit, formed in 1778 and fought bravely in the Battle of Rhode Island",
        "If each state were the size of Rhode Island, the United States would have 3,131.5 states",
        "Contrary to popular belief, Rhode Island is not located in New York. However, there are places named Rhode Island in both New York and Texas",
        "In 1774, the first circus in the U.S. was held in Newport",
        "Rhode Island is the smallest state in the U.S. You could fit 547.09 Rhode Islands within Alaska, the largest state",
        "The White Horse Tavern, built in 1673 in Newport, is believed to be the oldest tavern building in the U.S.",
        "The first American breed of horse, the Narragansett Pacer, was developed in Rhode Island",
        "Rhode Island's tidal shoreline, including bays, coves, and offshore islands, measures 384 miles",
        "Newport's Touro Synagogue, built in 1763, is the oldest surviving synagogue building in the U.S.",
        "On May 29, 1790, Rhode Island became the last of the original thirteen colonies to ratify the U.S. Constitution",
        "Despite common misconceptions, Rhode Island is not located in New York",
        "The First Rhode Island Regiment, the first black American army unit, formed in Rhode Island in 1778",
        "The Rhode Island Greening Apple, developed around 1650, is the state fruit",
    ],
};

const getRhodeIslandData = () => rhodeIslandData;

module.exports = {
    getRhodeIslandData,
};
