const historyFacts = [
    {
        year: 1636,
        text: "Roger Williams is exiled from the Massachusetts Bay Colony and founds Providence.",
        media: "https://www.flickr.com/photos/152474172@N05/36682959364/in/dateposted-public/",
        mediaCredit: "Wikimedia",
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/36682959364/in/dateposted-public/",
    },
    {
        year: 1644,
        text: "Aquidneck Island is renamed Rhode Island.",
        media: "https://www.flickr.com/photos/152474172@N05/36681812014/in/dateposted-public/",
        mediaCredit: "Rhode Island State Archives",
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/36681812014/in/dateposted-public/",
    },
    {
        year: 1647,
        text: "Portsmouth, Newport, and Warwick create a system of government for Providence Plantations that establishes the rights of its citizens.",
        media: "https://www.flickr.com/photos/152474172@N05/36723549033/in/dateposted-public/",
        mediaCredit: "Rhode Island State Archives",
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/36723549033/in/dateposted-public/",
    },
    {
        year: 1652,
        text: "Rhode Island passes a law banning slavery, however it is not well enforced.",
        media: "https://www.flickr.com/photos/152474172@N05/36723701233/in/dateposted-public/",
        mediaCredit: "Rhode Island State Archives",
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/36723701233/in/dateposted-public/",
    },
    {
        year: 1663,
        text: "The Royal Charter guarantees Rhode Islanders freedom of religion and the right to govern themselves. The original Royal Charter is on display in the Rhode Island State House.",
        media: "https://www.flickr.com/photos/152474172@N05/23524289808/in/dateposted-public/",
        mediaCredit: "Rhode Island State Archives",
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/23524289808/in/dateposted-public/",
    },
    {
        year: 1675,
        text: "Increasing tensions between colonists and Native Americans lead to war. King Philip's War (named for Wampanoag chief Metacom, also known as King Philip) results in great loss of life and land for Native peoples.",
        media: "https://www.flickr.com/photos/152474172@N05/36723692033/in/dateposted-public/",
        mediaCredit: "Rhode Island State Archives",
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/36723692033/in/dateposted-public/",
    },
    {
        year: 1770,
        text: "Brown University is founded in Warren, Rhode Island. It is the seventh-oldest institution of higher education in the United States.",
        media: "https://www.flickr.com/photos/152474172@N05/36723702173/in/dateposted-public/",
        mediaCredit: "Rhode Island State Archives",
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/36723702173/in/dateposted-public/",
    },
    {
        year: 1772,
        text: "In one of the earliest major acts of rebellion against England, Rhode Islanders attack and burn the English revenue schooner HMS Gaspee. For more information about the Gaspee attack, visit our Gaspee Timeline.",
        media: null,
        mediaCredit: null,
        mediaThumbnail: null,
    },
    {
        year: 1773,
        text: "Eighteen months after the Gaspee attack, Massachusetts colonists participate in the Boston Tea Party.",
        media: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Boston_Tea_Party_w.jpg",
        mediaCredit: null,
        mediaCaption: null,
        mediaThumbnail: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Boston_Tea_Party_w.jpg",
    },
    {
        year: 1774,
        text: "Providence citizens are the first to propose the idea of a Continental Congress at their town meeting.",
        media: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Providence_in_colonial_times_%281912%29_%2814782832555%29.jpg",
        mediaCredit: null,
        mediaCaption: null,
        mediaThumbnail:
            "https://upload.wikimedia.org/wikipedia/commons/c/ca/Providence_in_colonial_times_%281912%29_%2814782832555%29.jpg",
    },
    {
        year: 1776,
        text: "On May 4, Rhode Island declares independence from Britain, two months before the Declaration of Independence is signed.",
        media: "https://www.flickr.com/photos/152474172@N05/47418540742/in/dateposted-public/",
        mediaCredit: "National Archives",
        mediaCaption: null,
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/47418540742/in/dateposted-public/",
    },
    {
        year: 1780,
        text: "Rhode Island ratifies the Articles of Confederation.",
        media: "https://www.flickr.com/photos/152474172@N05/47418540742/in/dateposted-public/",
        mediaCredit: "National Archives",
        mediaCaption: null,
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/47418540742/in/dateposted-public/",
    },
    {
        year: 1790,
        text: "Rhode Island is the last of the original 13 colonies to ratify the United States Constitution.",
        media: "https://www.flickr.com/photos/152474172@N05/48049171746/in/dateposted-public/",
        mediaCredit: "Wikimedia",
        mediaCaption: null,
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/48049171746/in/dateposted-public/",
    },
    {
        year: 1800,
        text: "During the 1800s, Rhode Island experiences the Industrial Revolution, becoming a center for textile manufacturing and trade.",
        media: "https://www.flickr.com/photos/152474172@N05/48439362716/in/dateposted-public/",
        mediaCredit: "Wikimedia",
        mediaCaption: null,
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/48439362716/in/dateposted-public/",
    },
    {
        year: 1842,
        text: "Thomas Dorr leads an unsuccessful rebellion to expand voting rights in Rhode Island, resulting in the creation of a new state constitution.",
        media: "https://upload.wikimedia.org/wikipedia/commons/3/37/Dorr_war.jpg",
        mediaCredit: "Wikimedia",
        mediaCaption: null,
        mediaThumbnail: "https://upload.wikimedia.org/wikipedia/commons/3/37/Dorr_war.jpg",
    },
    {
        year: 1900,
        text: "By the 20th century, Rhode Island transitions from an industrial to a service-based economy, with a focus on education, healthcare, and tourism.",
        media: "https://upload.wikimedia.org/wikipedia/commons/3/37/Dorr_war.jpg",
        mediaCredit: "Wikimedia",
        mediaCaption: null,
        mediaThumbnail: "https://upload.wikimedia.org/wikipedia/commons/3/37/Dorr_war.jpg",
    },
    {
        year: 1920,
        text: "The 19th Amendment is ratified, granting women the right to vote. Rhode Island had already granted partial suffrage in 1887.",
        media: "https://www.flickr.com/photos/152474172@N05/49006503726/in/dateposted-public/",
        mediaCredit: "Wikimedia",
        mediaCaption: null,
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/49006503726/in/dateposted-public/",
    },
    {
        year: 1938,
        text: "The Great New England Hurricane of 1938 devastates Rhode Island.",
        media: "https://www.flickr.com/photos/152474172@N05/52703949587/in/dateposted-public/",
        mediaCredit: "Rhode Island State Archives",
        mediaCaption: null,
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/52703949587/in/dateposted-public/",
    },
    {
        year: 1969,
        text: "The Newport Bridge, later named for Senator Claiborne Pell, becomes the longest suspension bridge in New England.",
        media: "https://flic.kr/p/2otYvpr",
        mediaCredit: "Rhode Island State Archives",
        mediaThumbnail: "https://flic.kr/p/2otUFDW",
    },
    {
        year: 1978,
        text: "A February blizzard blankets Rhode Island with 2-4 feet of snow and paralyzes the state.",
        media: "https://www.flickr.com/photos/152474172@N05/52704953153/in/dateposted-public/",
        mediaCredit: "Rhode Island State Archives",
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/52704953153/in/dateposted-public/",
    },
    {
        year: 1994,
        text: "The first WaterFire lighting is made possible by a complete redesign of Providence which includes uncovering long buried rivers and moving its train station.",
        media: null,
        mediaCredit: null,
        mediaThumbnail: "http://waterfire.org/wp-content/uploads/2012/04/RISD-Panorama.jpg",
    },
    {
        year: 2016,
        text: "America's first off-shore wind farm is built off the coast of Block Island.",
        media: "https://youtu.be/p29MnJL4IlQ",
        mediaCredit: "Fred Olsen Windcarrier",
        mediaThumbnail: "https://youtu.be/p29MnJL4IlQ",
    },
    {
        year: 2020,
        text: 'In a state-wide referendum, Rhode Islanders vote to remove "and Providence Plantations" from the state\'s name.',
        media: "https://www.flickr.com/photos/152474172@N05/51129406574/in/dateposted-public/",
        mediaCredit: "Elections Division, RI Department of State",
        mediaThumbnail: "https://www.flickr.com/photos/152474172@N05/51129406574/in/dateposted-public/",
    },
];

const getHistoryData = () => historyFacts;


module.exports = {
    getHistoryData,
};
